#!/usr/bin/env python3
"""Generate OKDesignSystem palette Swift files from the desktop theme CSS.

Reads textlingo-desktop/src/styles/themes/{california,tokyo,seoul}.css,
converts every OKLCH token to Display P3, and emits
Packages/OpenKotoKit/Sources/OKDesignSystem/Generated/Palette+<Theme>.swift.

Usage:  python3 scripts/generate_palettes.py
Re-run whenever the desktop CSS themes change. Do not edit generated files.
"""

import math
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CSS_DIR = REPO_ROOT / "textlingo-desktop" / "src" / "styles" / "themes"
OUT_DIR = (
    REPO_ROOT / "openkoto-ios" / "Packages" / "OpenKotoKit"
    / "Sources" / "OKDesignSystem" / "Generated"
)

THEMES = ["california", "tokyo", "seoul"]

# Semantic tokens consumed by ThemeTokens (design doc §7.1).
TOKENS = [
    "background", "foreground", "card", "card-foreground",
    "primary", "primary-foreground", "secondary", "secondary-foreground",
    "muted", "muted-foreground", "accent", "accent-foreground",
    "destructive", "destructive-foreground", "border", "input", "ring",
]


def oklch_to_p3(l: float, c: float, h_deg: float) -> tuple[float, float, float]:
    """OKLCH -> linear Display P3 -> gamma-encoded P3, clamped to [0, 1]."""
    h = math.radians(h_deg)
    a, b = c * math.cos(h), c * math.sin(h)
    # OKLab -> non-linear LMS
    l_ = l + 0.3963377774 * a + 0.2158037573 * b
    m_ = l - 0.1055613458 * a - 0.0638541728 * b
    s_ = l - 0.0894841775 * a - 1.2914855480 * b
    L, M, S = l_ ** 3, m_ ** 3, s_ ** 3
    # LMS -> XYZ (D65)
    x = 1.2270138511 * L - 0.5577999807 * M + 0.2812561490 * S
    y = -0.0405801784 * L + 1.1122568696 * M - 0.0716766787 * S
    z = -0.0763812845 * L - 0.4214819784 * M + 1.5861632204 * S
    # XYZ (D65) -> linear Display P3
    r = 2.4934969119 * x - 0.9313836179 * y - 0.4027107845 * z
    g = -0.8294889696 * x + 1.7626640603 * y + 0.0236246858 * z
    bl = 0.0358458302 * x - 0.0761723893 * y + 0.9568845240 * z

    def encode(v: float) -> float:  # P3 uses the sRGB transfer curve
        v = min(1.0, max(0.0, v))
        return 12.92 * v if v <= 0.0031308 else 1.055 * (v ** (1 / 2.4)) - 0.055

    return encode(r), encode(g), encode(bl)


def parse_block(css: str, dark: bool, theme: str) -> dict[str, tuple[float, float, float]]:
    marker = rf"\.theme-{theme}{'\\.dark' if dark else ''}\s*{{"
    match = re.search(marker, css)
    if not match:
        raise SystemExit(f"block not found: {theme} dark={dark}")
    block = css[match.end(): css.index("}", match.end())]
    out = {}
    for name in TOKENS:
        m = re.search(
            rf"--{name}:\s*oklch\(([\d.]+)\s+([\d.]+)\s+([\d.]+)\)", block
        )
        if not m:
            raise SystemExit(f"token --{name} missing in {theme} dark={dark}")
        out[name] = oklch_to_p3(*(float(g) for g in m.groups()))
    return out


def swift_ident(token: str) -> str:
    parts = token.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def emit(theme: str, light: dict, dark: dict) -> str:
    name = theme.capitalize()
    lines = [
        "// Generated by scripts/generate_palettes.py — DO NOT EDIT.",
        f"// Source: textlingo-desktop/src/styles/themes/{theme}.css",
        "",
        "import SwiftUI",
        "",
        f"extension ThemePalette {{",
        f"    public static let {theme} = ThemePalette(",
    ]
    for mode, table in (("light", light), ("dark", dark)):
        lines.append(f"        {mode}: ThemeTokens(")
        entries = []
        for token in TOKENS:
            r, g, b = table[token]
            entries.append(
                f"            {swift_ident(token)}: Color(.displayP3, "
                f"red: {r:.4f}, green: {g:.4f}, blue: {b:.4f})"
            )
        lines.append(",\n".join(entries))
        lines.append("        )," if mode == "light" else "        )")
    lines += ["    )", "}", ""]
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        css = (CSS_DIR / f"{theme}.css").read_text()
        light = parse_block(css, dark=False, theme=theme)
        dark = parse_block(css, dark=True, theme=theme)
        path = OUT_DIR / f"Palette+{theme.capitalize()}.swift"
        path.write_text(emit(theme, light, dark))
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
